apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.node.name }}
  labels:
    app: {{ .Values.node.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.node.name }}
    spec:
      containers:
        - name: {{ .Values.node.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          env:
            - name: MYSQL_HOST
              value: {{ .Values.global.serviceName | quote}}
            - name: MYSQL_USER
              value: {{ .Values.global.user | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.global.password | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.global.database | quote }}
